trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore 
  displayName: 'Restore nuget packages'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'