trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore nuget packages'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
      command: 'build'
      arguments: '--no-restore  --configuration $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
      command: 'test'
      arguments: '--configuration $(buildConfiguration)'
     
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'

   